language: java
jdk:
- oraclejdk8
sudo: false
before_install:
- chmod +x ./gradlew
script:
- ./gradlew check
- ./gradlew javadoc
- ./gradlew jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)